import {defineStore} from "pinia"
export const playletStore=defineStore("playlet",{
	state:()=>{
		return{
			collect:[],
			like:[],
			history:[],
			search:[]
		}
	},
	actions:{
		save_collect(){
			uni.setStorage({
				key:"collect",
				data:this.collect
			})
		},
		save_like(){
			uni.setStorage({
				key:"like",
				data:this.like
			})
		},
		save_history(){
			uni.setStorage({
				key:"history",
				data:this.history
			})
		},
		update_collect(data){
			let index=this.collect.findIndex((item)=>{
				return item.id==data.id
			})
			if(index!=-1){
				this.collect.splice(index,1)
			}
			if(data.collect){
				this.collect.unshift(data)
			}	
			this.save_collect()
		},
		update_like(data){
			let index=this.like.findIndex((item)=>{
				return item.id==data.id
			})
			if(index!=-1){
				this.like.splice(index,1)
			}
			if(data.like){
				this.like.unshift(data)
			}	
			this.save_like()
		},
		update_history(data){
			let index=this.history.findIndex((item)=>{
				return item.id==data.id
			})
			if(index!=-1){
				this.history.splice(index,1)
			}
			if(data.progress){
				this.history.unshift(data)
			}	
			this.save_history()
		},
		get_collect(){
			uni.getStorage({
				key:"collect",
				success:(res)=>{
					this.collect=res.data
				},
				fail:()=>{
					this.collect=[]
				}
			})
		},
		get_like(){
			uni.getStorage({
				key:"like",
				success:(res)=>{
					this.like=res.data
				},
				fail:()=>{
					this.like=[]
				}
			})
		},
		get_history(){
			uni.getStorage({
				key:"history",
				success:(res)=>{
					this.history=res.data
				},
				fail:()=>{
					this.history=[]
				}
			})
		},
		save_search(){
			uni.setStorage({
				key:"search",
				data:this.search
			})
		},
		update_search(data){
			let index=this.search.findIndex((item)=>{
				return item==data
			})
			if(index!=-1){
				this.search.splice(index,1)
			}
			this.search.unshift(data)
			this.save_search()
		},
		get_search(){
			uni.getStorage({
				key:"search",
				success:(res)=>{
					this.search=res.data
					console.log(this.search);
				}
			})
		},
		remove_search(){
			uni.removeStorage({
				key:"search",
				success:()=>{
					console.log("异步删除成功");
				}
			})
			this.search=[]
			this.save_search()
			this.get_search()
		}
	}
})